name: "Notion to GH Issues"
description: "Queries a Notion database and creates GitHub Issues for the records given a condition"
inputs:
  githubToken:
    description: "GitHub Secret"
    required: true
  notionDbId:
    description: "Id for Notion database to query"
    required: true
  notionApiToken:
    description: "Notion API token"
    required: true
  tagColumnName:
    description: "Notion database property to look at"
    required: true
  tagValue:
    description: "Notion database cell value to filter on"
    required: true
runs:
  using: "node16"
  main: "index.js"
